# Generated by Django 3.0.8 on 2020-08-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyIndexFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('telephone', models.CharField(max_length=11, verbose_name='联系方式')),
                ('email', models.CharField(max_length=128, verbose_name='邮箱')),
                ('message', models.TextField(verbose_name='留言')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否已审核')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '首页提交',
                'verbose_name_plural': '首页提交',
            },
        ),
        migrations.CreateModel(
            name='CompanyPageFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('telephone', models.CharField(max_length=11, verbose_name='联系方式')),
                ('gift', models.CharField(max_length=128, verbose_name='赠品')),
                ('baby_age', models.CharField(max_length=128, verbose_name='婴儿年龄')),
                ('message', models.TextField(verbose_name='留言')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否已审核')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '免费领取',
                'verbose_name_plural': '免费领取',
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='赠品名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '赠品管理',
                'verbose_name_plural': '赠品管理',
            },
        ),
    ]
