# Generated by Django 3.0.8 on 2020-08-11 10:55

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('telephone', models.CharField(max_length=11, unique=True, verbose_name='手机号码')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='邮箱')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='真实姓名')),
                ('web_url', models.CharField(blank=True, max_length=128, null=True, verbose_name='个人网站地址')),
                ('qq', models.CharField(blank=True, max_length=56, null=True, verbose_name='QQ')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生年月')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=6, verbose_name='性别')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='用户头像')),
                ('introduce', models.CharField(blank=True, max_length=256, null=True, verbose_name='个人介绍')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='所在地')),
                ('jobs', models.CharField(blank=True, max_length=56, null=True, verbose_name='工作')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('data_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
