# Generated by Django 3.0.8 on 2020-08-11 10:55

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='公司名称')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '关于我们',
                'verbose_name_plural': '关于我们',
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='公司名称')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '联系我们',
                'verbose_name_plural': '联系我们',
            },
        ),
        migrations.CreateModel(
            name='CompanyLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='链接名称')),
                ('pic', models.ImageField(upload_to='links/', verbose_name='图片')),
                ('url', models.URLField(default='https://www.baidu.com', verbose_name='链接')),
                ('index', models.IntegerField(default=1, help_text='数字越大越靠前', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '扩展链接',
                'verbose_name_plural': '扩展链接',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, verbose_name='序列号')),
                ('name', models.CharField(max_length=128, verbose_name='商品名称')),
                ('desc', models.CharField(max_length=128, verbose_name='描述')),
                ('thumbnail', models.ImageField(help_text='尺寸320*240', upload_to='goods_thumbnail/', verbose_name='缩略图')),
                ('buy_link', models.URLField(blank=True, help_text='选填', null=True, verbose_name='购买链接')),
                ('is_index', models.BooleanField(default=False, verbose_name='是否首页显示')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击量')),
            ],
            options={
                'verbose_name': '商品管理',
                'verbose_name_plural': '商品管理',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('is_index', models.BooleanField(default=False, verbose_name='是否首页显示')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, verbose_name='序列号')),
                ('title', models.CharField(max_length=128, verbose_name='文章标题')),
                ('desc', models.CharField(max_length=128, verbose_name='文章简介')),
                ('thumbnail', models.ImageField(help_text='尺寸420*200', upload_to='news_thumbnail/', verbose_name='文章缩略图')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_index', models.BooleanField(default=True, verbose_name='是否首页显示')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '文章管理',
                'verbose_name_plural': '文章管理',
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('desc', models.CharField(max_length=128, verbose_name='简介')),
                ('thumbnail', models.ImageField(upload_to='strength/', verbose_name='封面')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_index', models.BooleanField(default=True, verbose_name='是否首页显示')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '实力保证',
                'verbose_name_plural': '实力保证',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('desc', models.CharField(max_length=128, verbose_name='描述')),
                ('thumbnail', models.ImageField(help_text='尺寸：480*300', upload_to='video/', verbose_name='视频封面')),
                ('video', models.FileField(upload_to='video_file/', verbose_name='上传视频')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_index', models.BooleanField(default=True, verbose_name='是否首页显示')),
                ('source', models.CharField(choices=[('web', '网络'), ('company', '安姐')], default='company', max_length=50, verbose_name='视频来源')),
            ],
            options={
                'verbose_name': '视频管理',
                'verbose_name_plural': '视频管理',
            },
        ),
        migrations.CreateModel(
            name='NewsSEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(default='', help_text='请以英文符号","分开', max_length=128, verbose_name='文章关键词')),
                ('description', models.CharField(default='', help_text='文章的描述', max_length=200, verbose_name='文章描述')),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='newsnewsseo_news', to='company.News', verbose_name='文章')),
            ],
        ),
        migrations.CreateModel(
            name='NewsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='newsdetail_news', to='company.News', verbose_name='文章')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_news', to='company.NewsCategory', verbose_name='文章分类'),
        ),
        migrations.CreateModel(
            name='GoodsTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名称')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_tags_goods', to='company.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品标签',
                'verbose_name_plural': '商品标签',
            },
        ),
        migrations.CreateModel(
            name='GoodsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
                ('goods', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goodsdetail_goods', to='company.Goods', verbose_name='商品')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(help_text='尺寸480*300', upload_to='goods_banner/', verbose_name='轮播图片')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodsbanners_goods', to='company.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品轮播图',
                'verbose_name_plural': '商品轮播图',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_goods', to='company.GoodsCategory', verbose_name='所属分类'),
        ),
    ]
